### PR TITLE
Added css webkit scrollbar styles

### PR DESCRIPTION
**Pull request by james1236**
Change Image

### CODE REVIEW

**Comment by stevedekorte** [comment]
Hey James, thanks for the pull request. Personally, I prefer the existing style but I'm open to adding this as an option. If I add a Settings menu for UI options with a sample toggle switch, would you be willing to hook up the css modification code for this?

**Comment by james1236** [comment]
No problem, having this as a specific setting seems a bit messy though. Might I suggest a kind of theme system as a setting where a directory of "themes" (css files) can be loaded that override some elements of the UI? In future these could also be user submitted if you desire.

**Comment by james1236** [comment]
Sounds great :) Do you have any plans to split up the index.html file into imported css and javascript? At 3mb and over 100k lines I think it's getting pretty unmanageable.

**Comment by stevedekorte** [comment]
The index file is generated by the archive.js script. 
I use VS Code editing tool with settings (included in the project) which runs this script and launches Chrome.

**Comment by stevedekorte** [comment]
Because the imports need to be done in a particular order. If you want to avoid the build step, there's an index_incremental.html file that has a Javascript import system that will load all the resources individually but it's much slower than the index.html if the files aren't local.

**Comment by stevedekorte** [comment]
I've added an new issue for supporting UI settings so I'll close this one.

**Pull request closed without merging**
